# Generated by Django 2.2.4 on 2019-10-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('baseobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Base.BaseObject')),
                ('subject', models.CharField(max_length=255)),
                ('hypothesis', models.CharField(max_length=4096)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('planning', 'Planning')], default='planning', max_length=32)),
            ],
            bases=('Base.baseobject',),
        ),
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('basefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Base.BaseField')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('numeric', 'Numeric'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], default='text', max_length=255)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Study.Study')),
            ],
            bases=('Base.basefield',),
        ),
    ]
